name: CI/CD
on: 
  [push,workflow_dispatch]
jobs:
  j_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: s_lint_test_build
        run: | 
          npm ci
          npm run lint
          npm run test
          npm run build

  j_deploy:
    runs-on: ubuntu-latest
    needs: j_build
    steps:
      - name: s_deploy
        run: echo "Deploy..."
        
  
